### ISSUE TITLE
Script specifies /bin/sh, but then uses bash-specific syntax

### ISSUE THREAD

**Issue by phrxmd** [mriza/winbox-installer#12]
The first line of the install script specifies `#!/bin/sh`, but then it uses bash-specific syntax like `if [[` (the proper `sh` supports only `[`).

The way it is now, the script works only on systems where `/bin/sh` is a symlink to `bash`. On systems that have a true `sh`, or where `/bin/sh` is a symlink to some other shell, the installer script fails. For example, for me on Linux Mint 19, where `/bin/sh` is a symlink to `dash`, it fails.

Either change the shebang line to `#!/bin/bash` so that the script runs on a shell that supports its syntax; or change the syntax of the script to make less assumptions about the shell.

**Comment by phrxmd** [comment]
Proposed fix in #13.

**Comment by mriza** [comment]
Great. Thanks
