### ISSUE TITLE
Script not install correct wine

### ISSUE THREAD

**Issue by toperx** [mriza/winbox-installer#14]
> System: Host: pzc Kernel: 4.15.0-20-generic x86_64 bits: 64 compiler: gcc v: 7.3.0
> Desktop: Cinnamon 4.0.9 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa
> base: Ubuntu 18.04 bion

ic

`toper@pzc:/usr/local/bin$ ./winbox.sh 
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: Ошибка в формате EXE для Z:\usr\local\bin\winbox.exe.
`

afther install wine32 its work normal

**Comment by mriza** [comment]
I don't use Ubuntu/Mint, so I can't confirm this. Right now the script has error (checking is wine is installed or not by invoking wine command). So the error maybe not directly related with the end result. I will try to reproduce the error in a VM

**Comment by karlisk** [comment]
On Ubuntu 19.10 Eoan installation went fine without problems Wine version: wine-5.0-rc3 (Staging).

Wine in use is from WineHQ repos at https://wiki.winehq.org/Ubuntu
