### ISSUE TITLE
Maybe bash not sh

### ISSUE THREAD

**Issue by gil-obradors** [mriza/winbox-installer#2]
I have changed the first line to #!/bin/bash
If not, there are some errors executing it.
I think is BASH nor SH

Thanks

**Comment by mriza** [comment]
Nope, #!/bin/sh is the right one. Not everyone using bash, some are using dash, or maybe zsh, etc. Most of linux systems are linking /bin/sh to their default shell like bash or dash. If your system doesn't have /bin/sh you can make the symbolic link manually.
ln -s /bin/bash /bin/sh

**Comment by phrxmd** [comment]
@gil-obradors is right. It's a good idea in principle to support multiple shells, but then you shouldn't use bash-specific syntax like `if [[`. If you use that kind of syntax, you need to specify a shell that supports it.
