### ISSUE TITLE
Add curl as a dependency in the README file

### ISSUE THREAD

**Issue by nashamri** [mriza/winbox-installer#5]
Hello there,

I tried to run this script on a bran new installation of ubuntu 18.04 and by default `curl` isn't installed. Maybe adding this info to the README file will help others.

Thanks!

**Comment by mriza** [comment]
As per latest update, the package has been added to dependencies installation. CURL should be available as the downloader.

**Comment by nashamri** [comment]
Cheers! :+1:

**Comment by mriza** [comment]
thank you @nashamri  :+1:
