### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by wolfen351** [mriza/winbox-installer#6]
Also need to install the appropriate fonts?

**Comment by mriza** [comment]
You can install MS Core Fonts

**Comment by wolfen351** [comment]
true, but it would be cool if the installer did everything needed to, you know, install it! :)

Also, in all seriousness, I think ms core fonts is not _quite_ enough, at least on my machine the cursor still gets 'behind' the text

![image](https://user-images.githubusercontent.com/5477547/40203056-1e8ee1a0-5a78-11e8-9ed6-30fe6e05b691.png)

**Comment by mriza** [comment]
I think that is more relevant to wine tweaking while this little script purpose is just an installation helper. It's still true and I agree with your idea about doing everything that needed to be done, maybe like unattended mode thing, or additional menu to select some setting(s).
I will try to write some code although can't promise new update. Thank you for your idea.

**Comment by mriza** [comment]
Hi @wolfen351 The font rendering will be improved with the latest update
